apiVersion: apps/v1
kind: Deployment
metadata:
  name: microsim-landing
  namespace: microsim-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microsim-landing
  template:
    metadata:
      labels:
        app: microsim-landing
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            # HTML + CSS
            - name: html
              mountPath: /usr/share/nginx/html

            # Images (favicon, logo, bg)
            - name: assets
              mountPath: /usr/share/nginx/html/img
              readOnly: true
      volumes:
        - name: html
          configMap:
            name: microsim-landing-html

        - name: assets
          configMap:
            name: microsim-landing-assets
---
apiVersion: v1
kind: Service
metadata:
  name: microsim-landing
  namespace: microsim-dev
spec:
  selector:
    app: microsim-landing
  ports:
    - port: 80
      targetPort: 80

