apiVersion: apps/v1
kind: Deployment
metadata:
  name: microsim
  namespace: microsim-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microsim
  template:
    metadata:
      labels:
        app: microsim
    spec:
      containers:
        - name: microsim
          image: yurishkuro/microsim:latest
          command: ["/bin/sh", "-c"]
          args:
            - microsim frontend & sleep infinity
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: microsim
  namespace: microsim-dev
spec:
  selector:
    app: microsim
  ports:
    - port: 80
      targetPort: 8080

