apiVersion: batch/v1
kind: Job
metadata:
  name: microsim
  namespace: microsim-dev
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: microsim
        image: yurishkuro/microsim:latest
        args:
          - frontend
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://jaeger-collector.observability.svc.cluster.local:4318
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://jaeger-collector.observability.svc.cluster.local:4318/v1/traces
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"

