apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: observability-tls
  namespace: observability
spec:
  secretName: observability-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - grafana.microsim.dev.piratesec.com
    - traces.microsim.dev.piratesec.com

